//
// Created by luna on 09/12/2021.
//

#ifndef WARZONE2100_ORDER_H
#define WARZONE2100_ORDER_H

#include "lib/framework/vector.h"
#include "basedef.h"

static constexpr auto ATTACK_RANGE_MASK = 0x000003;

enum class ORDER_TYPE
{
	NONE,
	STOP,
	MOVE,
	ATTACK,
	BUILD,
	HELP_BUILD,
	LINE_BUILD,
	DEMOLISH,
	REPAIR,
	OBSERVE,
	FIRE_SUPPORT,
	RETURN_TO_BASE,
	RETURN_TO_REPAIR,
	EMBARK,
	DISEMBARK,
	ATTACK_TARGET,
	COMMANDER_SUPPORT,
	BUILD_MODULE,
	RECYCLE,
	TRANSPORT_OUT,
	TRANSPORT_IN,
	TRANSPORT_RETURN,
	GUARD,
	DROID_REPAIR,
	RESTORE,
	SCOUT,
	PATROL,
	REARM,
	RECOVER,
	RTR_SPECIFIED,
	CIRCLE,
	HOLD
};

enum class SECONDARY_ORDER
{
	ATTACK_RANGE,
	REPAIR_LEVEL,
	ATTACK_LEVEL,
	ASSIGN_PRODUCTION,
	ASSIGN_CYBORG_PRODUCTION,
	CLEAR_PRODUCTION,
	RECYCLE,
	PATROL,
	HALT_TYPE,
	RETURN_TO_LOC,
	FIRE_DESIGNATOR,
	ASSIGN_VTOL_PRODUCTION,
	CIRCLE
};

enum class SECONDARY_STATE
{
    NONE = 0x000000,
    /**< no state. */
    ATTACK_RANGE_SHORT = 0x000001,
    ATTACK_RANGE_LONG = 0x000002,
    ATTACK_RANGE_OPTIMUM = 0x000003,
    REPAIR_LEVEL_LOW = 0x000004,
    REPAIR_LEVEL_HIGH = 0x000008,
    REPAIR_LEVEL_NEVER = 0x00000c,
    ATTACK_LEVEL_ALWAYS = 0x000010,
    ATTACK_LEVEL_ATTACKED = 0x000020,
    ATTACK_LEVEL_NEVER = 0x000030,
    HALT_HOLD = 0x000040,
    HALT_GUARD = 0x000080,
    HALT_PURSUE = 0x0000c0,
    RECYCLE_SET = 0x000100,
    RTL_REPAIR = 0x080000,
    RTL_BASE = 0x100000,
    RTL_TRANSPORT = 0x200000,
    PATROL_SET = 0x400000,
    CIRCLE_SET = 0x400100,
    FIREDES_SET = 0x800000
};

struct Order
{
	using enum ORDER_TYPE;

	ORDER_TYPE type;
	Vector2i position;
	Simple_Object* target_object;
};

#endif // WARZONE2100_ORDER_H
